### ISSUE TITLE
Resolving Large File Upload Issues in Kubernetes with Nginx Ingress and Cloudflare

### ISSUE THREAD

**Issue by Raihan-009** [Raihan-009/swe-learning-docs#3]
## Problem Statement

Users attempting to upload files larger than 1MB to our API service were receiving Cloudflare Error 520 (Unknown Connection Issue). Small files under 1MB uploaded successfully, but any file exceeding this limit would consistently fail.

Error message received:
```
Web server is returning an unknown error Error code 520
Visit cloudflare.com for more information.
There is an unknown connection issue between Cloudflare and the origin web server.
As a result, the web page can not be displayed.
```

## Root Cause Analysis

The issue stemmed from multiple layers of configuration limits:

1. **Nginx Ingress Controller Limitations**: By default, the Nginx Ingress controller in Kubernetes has a body size limit of 1MB, which was restricting larger file uploads.

2. **Resource Constraints**: The Kubernetes deployment lacked defined resource limits and requests, potentially leading to resource exhaustion during large file uploads.

3. **Timeout Configuration**: Default timeout settings were insufficient for large file uploads, causing connections to drop before completion.

4. **Cloudflare Limitations**: Cloudflare's default maximum upload size was also restricting larger files from being transmitted to the origin server.

## Solution

The issue was resolved by implementing configuration changes at multiple levels:

### 1. Kubernetes Deployment Updates

Added resource requests and limits to ensure pods have sufficient resources to handle large file uploads:

```yaml
containers:
  - name: file-backend
    image: your-image:tag
    imagePullPolicy: Always
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
```

### 2. Nginx Ingress Controller Configuration

Modified the Ingress resource with annotations to increase the allowed request body size and extend timeout limits:

```yaml
metadata:
  name: media-backend-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
```

These annotations:
- Set the maximum allowed request body size to 50MB
- Extended connection, send, and read timeouts to 600 seconds (10 minutes)

### 3. Cloudflare Configuration

For Cloudflare-protected services, additional steps were required:

1. Log into the Cloudflare dashboard
2. Navigate to the Rules section
3. Create a Page Rule for the upload endpoint(s)
4. Set "Increase Upload Size Limit" to at least 50MB

## Verification

After implementing these changes, users were able to successfully upload files up to 50MB without encountering the Cloudflare Error 520.

## Additional Considerations

- **Monitoring**: Implement monitoring for upload times and success rates to detect any regression in performance
- **Chunked Uploads**: For files larger than 50MB, consider implementing chunked uploads in your application
- **Progressive Enhancement**: Ensure your application provides appropriate feedback during large file uploads
- **Content Validation**: Implement server-side validation for file size, type, and content

## Conclusion

File upload size limitations can appear at various layers in a modern cloud architecture. When troubleshooting such issues, it's essential to examine configuration at each layer: application server, container resources, ingress controller, and any CDN/proxy services like Cloudflare.

By properly configuring resources, timeouts, and body size limits throughout the stack, you can support larger file uploads while maintaining system stability.
